server:
  port: 8081
  context-path: /msg
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skare
    username: root
    password: 123456
  http:
    encoding:
      charset: UTF-8
      force: true
  mvc:
    view:
      prefix: /
      suffix: .jsp
mybatis:
  mapper-locations: com/baizhi/msg/dao/*Dao.xml
  type-aliases-package: com.baizhi.msg.entity